name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: |
        sudo apt-get update
        rustup target add aarch64-unknown-linux-gnu
        sudo apt-get install gcc-aarch64-linux-gnu
    - name: Build standard (config file)
      run: cargo build --target aarch64-unknown-linux-gnu --release

#    - name: Build defaults (no config file)
#      run: cargo build --target aarch64-unknown-linux-gnu --release --no-default-features

    - name: Copy binary
      run: cp target/aarch64-unknown-linux-gnu/release/argon_fan_controller ./

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1

    - name: Upload Release Asset
    - uses: actions/upload-artifact@v3
      with:
        name: argon_fan_controller_standard
        path: |
          argon_fan_controller 
          argon_fan_controller.service
          argon_fan_controller_cfg.yml
          deploy.sh
          remove.sh
          get_temps.sh
        content_type: application/zip
